import { Roboto, Geist_Mono } from 'next/font/google';
import './globals.css';
import SideNav from '@/components/side-nav';

// TODO: Cache Components adoption. Refactor this route so this opt-out can be removed.
// See: https://nextjs.org/docs/app/guides/migrating-to-cache-components
export const instant = false;

const fontSans = Roboto({
  variable: '--font-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SideNav /> */}
        {children}
      </body>
    </html>
  );
}
